export enum DomainCode {
	RESOURCE_ALREADY_EXISTS_ERROR = "RESOURCE_ALREADY_EXISTS_ERROR",
	RESOURCE_NOT_FOUND_ERROR = "RESOURCE_NOT_FOUND_ERROR",
	INVALID_CATEGORY_ERROR = "INVALID_CATEGORY_ERROR",
	INVALID_CODE_ERROR = "INVALID_CODE_ERROR",
	PASSWORDS_DONT_MATCH = "PASSWORDS_DONT_MATCH",
	DUPLICATE_GLOBAL_CATEGORY = "DUPLICATE_GLOBAL_CATEGORY",
	WRONG_CREDENTIALS_ERROR = "WRONG_CREDENTIALS_ERROR",
	INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
}
